export const images = {
  // OnBoardinfg Screen
  onboarding1: require("../assets/images/onboarding1.png"),
  onboarding2: require("../assets/images/onboarding2.png"),
  onboarding3: require("../assets/images/onboarding3.png"),
  goBtn: require("../assets/images/goBtn.png"),

  // Signup Screen
  backarrow: require("../assets/images/backarrow.png"),
  logoTitle: require("../assets/images/logoTitle.png"),
  logoTitle1: require("../assets/images/logoTitle1.png"),
  showEye: require("../assets/images/showEye.png"),
  hideEye: require('../assets/images/hideEye.png'),

  // Bottom Tabs
  homeFocus : require("../assets/images/homeFocus.png"),
  homeUnFocus : require("../assets/images/homeUnFocus.png"),
  categoryFocus : require("../assets/images/categoryFocus.png"),
  categoryUnFocus : require("../assets/images/categoryUnFocus.png"),
  cartFocus : require("../assets/images/cartFocus.png"),
  cartUnFocus : require("../assets/images/cartUnFocus.png"),
  myOrdersFocus : require("../assets/images/myOrdersFocus.png"),
  myOrdersUnFocus : require("../assets/images/myOrdersUnFocus.png"),
  settingsFocus : require("../assets/images/settingsFocus.png"),
  settingsUnFocus : require("../assets/images/settingsUnFocus.png"),

  // Home
  linearBG : require("../assets/images/linearBG.png"),
  groceriesLogo : require("../assets/images/groceriesLogo.png"),
  foodLogo : require("../assets/images/foodLogo.png"),
  locationIcon : require("../assets/images/locationIcon.png"),
  rightarrowBlue : require("../assets/images/rightarrowBlue.png"),
  notificationIcon : require("../assets/images/notificationIcon.png"),
  riceG : require("../assets/images/riceG.png"),
  pulsesG : require("../assets/images/pulsesG.png"),
  flourG : require("../assets/images/flourG.png"),
  cookingOilG : require("../assets/images/cookingOilG.png"),
  dairyG : require("../assets/images/dairyG.png"),
  spicesG : require("../assets/images/spicesG.png"),
  snacksG : require("../assets/images/snacksG.png"),
  beveragesG : require("../assets/images/beveragesG.png"),
  banner : require("../assets/images/banner.png"),
  milkBP : require("../assets/images/milkBP.png"),
  spicesBP : require("../assets/images/spicesBP.png"),
  snackBP : require("../assets/images/snackBP.png"),
  food1 : require("../assets/images/food1.png"),
  food2 : require("../assets/images/food2.png"),
  food3 : require("../assets/images/food3.png"),
  food4 : require("../assets/images/food4.png"),
  food5 : require("../assets/images/food5.png"),
  food6 : require("../assets/images/food6.png"),
  food7 : require("../assets/images/food7.png"),
  food8 : require("../assets/images/food8.png"),
  bs1 : require("../assets/images/bs1.png"),
  bs2 : require("../assets/images/bs2.png"),
  bs3 : require("../assets/images/bs3.png"),
  subwayLogo : require("../assets/images/subwayLogo.png"),
  macdonaldsLogo : require("../assets/images/macdonaldsLogo.png"),
  burgerKingLogo : require("../assets/images/burgerKingLogo.png"),
  locationIconOrange : require("../assets/images/locationIconOrange.png"),
  starEmpty: require("../assets/images/starEmpty.png"),

  // Setting
  profileIcon: require("../assets/images/profileIcon.png"),
  editProfileIcon: require("../assets/images/editProfileIcon.png"),
  changePasswordIcon: require("../assets/images/changePasswordIcon.png"),
  changeEmailIcon: require("../assets/images/changeEmailIcon.png"),
  changePhoneIcon: require("../assets/images/changePhoneIcon.png"),
  managePaymentIcon: require("../assets/images/managePaymentIcon.png"),
  myWishlistIcon: require("../assets/images/myWishlistIcon.png"),
  manageAddressIcon: require("../assets/images/manageAddressIcon.png"),
  availableOffersIcon: require("../assets/images/availableOffersIcon.png"),
  rateAppIcon: require("../assets/images/rateAppIcon.png"),
  shareAppIcon: require("../assets/images/shareAppIcon.png"),
  aboutUsIcon: require("../assets/images/aboutUsIcon.png"),
  contactUsIcon: require("../assets/images/contactUsIcon.png"),
  faqIcon: require("../assets/images/faqIcon.png"),
  privacyPolicyIcon: require("../assets/images/privacyPolicyIcon.png"),
  tcIcon: require("../assets/images/t&cIcon.png"),
  deleteProfileIcon: require("../assets/images/deleteProfileIcon.png"),
  logoutIcon: require("../assets/images/logoutIcon.png"),

  // Edit Profile
  profileBigIcon: require("../assets/images/profileBigIcon.png"),
  camera : require("../assets/images/camera.png"),
  downOrangeArrow: require("../assets/images/downOrangeArrow.png"),

  // Manage Address
  add: require("../assets/images/add.png"),
  checkfill: require("../assets/images/checkfill.png"),
  checkempty: require("../assets/images/checkempty.png"),
  edit: require("../assets/images/edit.png"),
  delete: require("../assets/images/delete.png"),

  //  My Wishlist
  redHeart : require("../assets/images/redHeart.png"),
  rice : require("../assets/images/rice.png"),
  oil : require("../assets/images/oil.png"),
  milk : require("../assets/images/milk.png"),
  atta : require("../assets/images/atta.png"),
  star : require("../assets/images/star.png"),
  search : require("../assets/images/search.png"),

  // Manage Payment 
  visaIcon : require("../assets/images/visaIcon.png"),
  mastercardIcon : require("../assets/images/mastercardIcon.png"),
  deleteWhiteBg : require("../assets/images/deleteWhiteBg.png"),
  calendar : require("../assets/images/calendar.png"),
};
