import { StyleSheet } from "react-native";
import { colors } from "../../constants/Colors";
import { fontSize } from "../../constants/FontSizes";
import { fontsfamily } from "../../constants/FontFamily";
import { ScreenDimensions } from "../../constants/utils/Dimensions";

export const styles = StyleSheet.create({
  /* vertical connector */
  line: {
    position: "absolute",
    left: 24 / 2 - 1,
    top: 24, // start exactly under the icon
    bottom: 0,
    width: 1,
  },
  // View styles
  vwMain: {
    flex: 10,
    backgroundColor: colors.blue4e,
  },
  vwOrderNumDateTimeTotal: {
    borderBottomColor: colors.greyd9_50,
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    marginLeft: 19,
    marginRight: 17,
    marginTop: 20,
    paddingBottom: 19,
  },
  vwOrderStatusMain: {
    marginLeft: 19,
    marginRight: 17,
    marginTop: 20,
    gap: 20,
  },
  vwOrderStatusItem: {
    flexDirection: "row",
    gap: 11,
    paddingBottom: 20,
  },
  vwLine: {
    height: 1,
    backgroundColor: colors.greyd9_50,
    marginHorizontal: 20,
    marginBottom: 20,
  },
  vwProductsItems: {
    backgroundColor: colors.white,
    borderRadius: 10,
    flexDirection: "row",
    overflow: "hidden",
  },
  vwProductImage: {
    width: 69,
    backgroundColor: colors.whiteff,
    justifyContent: "center",
    alignItems: "center",
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    overflow: "hidden",
    paddingVertical: 12.2,
  },
  vwProductItemDetails: {
    justifyContent: "space-between",
    marginRight: 14,
    marginVertical: 9,
    marginLeft: 11,
    flex: 1,
  },
  vwOrderDetails: {
    marginHorizontal: 20,
    gap: 15,
  },
  vwOrderDetailsItemMain: {
    gap: 11,
  },
  vwOrderDetailsItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  vwLineFull: {
    height: 1,
    backgroundColor: colors.grey62,
  },
  vwTotal: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  vwDriverDetails: {
    height: 79,
    backgroundColor: colors.white,
    borderRadius: 8,
    marginHorizontal: 20,
    gap: 12,
    paddingLeft: 12,
    paddingTop: 12,
    marginBottom: 20,
    flexDirection: "row",
  },
  vwDriverDetails1: {
    height: 79,
    backgroundColor: colors.white,
    borderRadius: 8,
    marginHorizontal: 20,
    gap: 12,
    paddingLeft: 12,
    marginBottom: 20,
    flexDirection: "row",
    alignItems: "center",
  },
  vwTrackCallChat: {
    height: 27.4,
    marginTop: 9,
    flexDirection: "row",
    alignItems: "center",
    gap: 15,
  },
  vwCancelledOrder: {
    flexDirection: "row",
    borderRadius: 10,
    backgroundColor: colors.white,
    paddingHorizontal: 16,
    paddingVertical: 20,
    gap: 15,
    flex: 1,
    marginBottom: 20,
  },
  vwOrderReturned: {
    flexDirection: "row",
    borderRadius: 10,
    backgroundColor: colors.white,
    paddingHorizontal: 16,
    paddingVertical: 20,
    marginBottom: 20,
    gap: 20,
    flex: 1,
  },

  // Text styles
  lblOrderNumber: {
    color: colors.white,
    fontSize: fontSize.size12,
    fontFamily: fontsfamily.regular,
    lineHeight: 16,
    marginBottom: 7,
  },
  lblOrderNumberValue: {
    color: colors.white,
    fontSize: fontSize.size16,
    fontFamily: fontsfamily.semibold,
  },
  lblOrderDateTime: {
    color: colors.white,
    fontSize: fontSize.size12,
    fontFamily: fontsfamily.regular,
    marginTop: 4,
  },
  lblTotal: {
    color: colors.white,
    fontSize: fontSize.size12,
    fontFamily: fontsfamily.regular,
    lineHeight: 16,
    marginBottom: 7,
    textAlign: "right",
  },
  lblTotalAmount: {
    color: colors.orange1c,
    fontSize: fontSize.size16,
    fontFamily: fontsfamily.semibold,
    textAlign: "right",
  },
  lblYourOrderisConfirmed: {
    fontSize: fontSize.size16,
    fontFamily: fontsfamily.semibold,
  },
  lblOrderStatusTitle: {
    fontSize: fontSize.size12,
    fontFamily: fontsfamily.semibold,
    lineHeight: 16,
    marginBottom: 2,
  },
  lblOrderStatusDate: {
    color: colors.greya7,
    fontSize: fontSize.size12,
    fontFamily: fontsfamily.regular,
  },
  lblItemsAdded: {
    color: colors.white,
    fontSize: fontSize.size16,
    fontFamily: fontsfamily.semiboldGolosText,
    marginBottom: 20,
  },
  lblProductName: {
    color: colors.black35,
    fontSize: fontSize.size14,
    fontFamily: fontsfamily.semibold,
    marginBottom: 5,
    lineHeight: 21,
  },
  lblProductPrice: {
    color: colors.blue4e,
    fontSize: fontSize.size14,
    fontFamily: fontsfamily.bold,
  },
  lblProductWeight: {
    color: colors.greya7,
    fontSize: fontSize.size12,
    fontFamily: fontsfamily.semibold,
  },
  lblQuantity: {
    color: colors.grey62,
    fontSize: fontSize.size14,
    fontFamily: fontsfamily.regularGolosText,
  },
  lblQuantityCount: {
    color: colors.blue4e,
    fontFamily: fontsfamily.semiboldGolosText,
    fontSize: fontSize.size14,
  },
  lblDelivertoName: {
    color: colors.white,
    fontFamily: fontsfamily.semiboldGolosText,
    fontSize: fontSize.size16,
    marginHorizontal: 20,
  },
  lblDelivertoAddress: {
    color: colors.greya7,
    fontFamily: fontsfamily.regularGolosText,
    fontSize: fontSize.size12,
    marginHorizontal: 20,
    marginTop: 7,
    lineHeight: 16,
    marginBottom: 20,
  },
  lblCancelOrderQue: {
    color: colors.red2e,
    fontFamily: fontsfamily.medium,
    fontSize: fontSize.size16,
    marginBottom: 5,
  },
  lblCancelOrderReason: {
    color: colors.greya7,
    fontFamily: fontsfamily.regular,
    fontSize: fontSize.size12,
    marginBottom: 5,
  },
  lblCancelOrderTime: {
    color: colors.red2e,
    fontFamily: fontsfamily.regular,
    fontSize: fontSize.size12,
  },
  lblReportIssueQue: {
    color: colors.black35,
    fontFamily: fontsfamily.mediumGolosText,
    fontSize: fontSize.size16,
    marginBottom: 5,
  },
  lblReportIssueDesc: {
    color: colors.greya7,
    fontFamily: fontsfamily.regular,
    fontSize: fontSize.size12,
  },
  lblRefundDesc: {
    color: colors.green4f,
    fontFamily: fontsfamily.medium,
    fontSize: fontSize.size12,
    marginTop: 5,
  },
  lblOrderDetails: {
    fontSize: fontSize.size16,
    fontFamily: fontsfamily.semibold,
    color: colors.white,
  },
  lblOrderDetailsTitle: {
    fontSize: fontSize.size14,
    fontFamily: fontsfamily.medium,
    color: colors.whiteff,
  },
  lblOrderDetailsValue: {
    fontSize: fontSize.size14,
    fontFamily: fontsfamily.semibold,
    color: colors.whiteff,
  },
  lblTotalBold: {
    fontSize: fontSize.size20,
    fontFamily: fontsfamily.bold,
    color: colors.white,
  },
  lblRateReview: {
    fontSize: fontSize.size12,
    fontFamily: fontsfamily.semibold,
    color: colors.black35,
    alignSelf: "center",
  },
  lblDriverInfo: {
    fontSize: fontSize.size16,
    fontFamily: fontsfamily.semibold,
    color: colors.white,
    marginHorizontal: 20,
    marginBottom: 10,
  },
  lblDriverName: {
    fontSize: fontSize.size16,
    fontFamily: fontsfamily.mediumGolosText,
    color: colors.blue4e,
  },
  lblTrack: {
    fontSize: fontSize.size10,
    fontFamily: fontsfamily.semibold,
    color: colors.blue4e,
  },

  //  Image styles
  imgOrderStatusIcon: {
    height: 24,
    width: 24,
  },
  imgDot: {
    height: 4,
    width: 4,
    marginHorizontal: 4,
  },
  imgCancel: {
    height: 24,
    width: 24,
  },
  imgRightArrowGrey: {
    height: 20,
    width: 20,
    position: "absolute",
    right: 10,
    alignSelf: "center",
  },
  imgRightArrow: {
    height: 20,
    width: 20,
    alignSelf: "center",
  },
  imgReportIssue: {
    height: 24,
    width: 24,
  },
  imgDriverProfile: {
    height: 42,
    width: 42,
    borderRadius: 42 / 2,
    overflow: "hidden",
  },
  imgTrackIcon: {
    height: 15,
    width: 15,
  },
  imgChatCall: {
    height: 27,
    width: 27,
  },
  imgStar: {
    height: 17.2,
    width: 17.2,
    marginRight: 2,
  },

  //   TouchableOpacity Styles
  btnCancelOrder: {
    borderRadius: 10,
    backgroundColor: colors.white,
    marginHorizontal: 20,
    marginBottom: 12,
    paddingVertical: 20,
    paddingLeft: 16,
    paddingRight: 28,
    flexDirection: "row",
    alignItems: "center",
    gap: 15,
  },

  btnReportIssue: {
    backgroundColor: colors.white,
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 20,
    paddingLeft: 16,
    paddingRight: 10,
    marginHorizontal: 20,
    marginBottom: 20,
    gap: 15,
  },
  btnRateReview: {
    borderRadius: 3,
    borderColor: colors.greya7,
    borderWidth: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 6,
    paddingVertical: 2.9,
    paddingHorizontal: 5,
    alignSelf: "flex-start",
    flexDirection: "row",
    gap: 2,
  },
  btnRateReviewText: {
    borderRadius: 3,
    borderColor: colors.greya7,
    borderWidth: 1,
    marginTop: 6,
    paddingVertical: 4.5,
    paddingHorizontal: 5,
    alignSelf: "flex-start",
  },
  btnTrack: {
    height: 27.4,
    width: 84.31,
    justifyContent: "center",
    alignItems: "center",
    gap: 5.27,
    borderRadius: 105.38,
    backgroundColor: colors.orange1c,
    flexDirection: "row",
  },

  // Modal style
  vwFilterModal: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: colors.black50,
  },
  vwFilterModalContainer: {
    width: ScreenDimensions.screenWidth,
    backgroundColor: colors.blue4e,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 16,
    paddingTop: 33,
  },
  vwEditDeleteReview: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  lblYourReview: {
    color: colors.white,
    fontSize: fontSize.size20,
    fontFamily: fontsfamily.bold,
    marginBottom: 36,
    textAlign: "center",
  },
  lblReviewDesc: {
    color: colors.greya7,
    fontSize: fontSize.size14,
    fontFamily: fontsfamily.regular,
    lineHeight: 20,
    marginTop: 10,
    marginBottom: 35.8,
    marginRight: 31,
  },
  imgStarModal: {
    height: 31.2,
    width: 31.2,
    marginRight: 6.98,
  },
  btnDelete: {
    height: 50,
    width: 50,
    borderRadius: 8,
    backgroundColor: colors.whiteff,
    justifyContent: "center",
    alignItems: "center",
  },
});
